### ISSUE TITLE
Conflicting description of MSWD (Reduced chi-squared) calculation.

### ISSUE THREAD

**Issue by DrMonkeyMan76** [pvermees/IsoplotR#1]
The method of calculating the reduced chi-squared (MSWD) in the get.york.mswd function (within York.R) value does not appear to be consistent with the description given in the IsoplotR reference manual v1.1, page 36, nor consistent with equation (4) detailed in the (in press) article available at http://www.ucl.ac.uk/~ucfbpve/papers/VermeeschGSF2018

Code of interest: York.R line 124

X2 <- X2 + 0.5*X %*% solve(E) %*% t(X)a

The factor of 0.5 does not appear in the quoted reference materials above; additionally a singular comparison with results described for Data set 3 in Table II of York's 2004 paper (Am. J. Phys, 72, 3, pp367-375) (https://aapt.scitation.org/doi/10.1119/1.1632486) reveals the above code determines the MSWD to be half that reported by York. Accordingly the subsequently derived p-value will be affected.

Hope this helps!

**Comment by pvermees** [comment]
Verified and fixed. Thank you!
