### ISSUE TITLE
Cov(a,b) in york.R should be calculated with the mean adjusted x and not the mean observed x

### ISSUE THREAD

**Issue by DrewGoodfellow** [pvermees/IsoplotR#2]
Hello,

In york.R,  covab is calculated on line 109:

`out$cov.ab <- -Xbar*sb^2`

In York et al. (2004), covariance between the slope and intercept estimates is calculated with the least squares adjusted mean x (page 369 of York et al.'s 2004 paper).
Should line 109 of York.R instead be (please note the lower case xbar)?

`out$cov.ab <- -xbar*sb^2`

Thank you in advance.

**Comment by pvermees** [comment]
Well spotted. Thanks!
