### ISSUE TITLE
Online IsoplotR model 3 regression error with provided data

### ISSUE THREAD

**Issue by RubyMarsden** [pvermees/IsoplotR#218]
Hi,
I was just having a look at the regression part of IsoplotR online and found that using the model 3 regression on the provided data seems to throw an error which says 'argument is of length zero'. Images below.
Could be a bug unless I need to input different data?

Many thanks,
Ruby

![image](https://github.com/pvermees/IsoplotR/assets/55971366/9b615b23-120a-4bb7-a723-6afc4cf31529)
<img width="963" alt="Screenshot 2024-03-03 183153" src="https://github.com/pvermees/IsoplotR/assets/55971366/df1e7d6a-24ee-40da-82da-e6e933f937d4">

**Comment by pvermees** [comment]
Dear Ruby,

Thanks for reporting the issue! It should be fixed now. Can you check (offline or on the London mirror)?

Pieter

**Comment by RubyMarsden** [comment]
Hi Pieter,

Yes that's fixed - thanks!

Ruby
