### ISSUE TITLE
I want to translate IsoPlotR into Chinese

### ISSUE THREAD

**Issue by flypigeon** [pvermees/IsoplotR#76]
I want to translate IsoPlotR into Chinese for domestic users.Can you give me authorization? What's more, how should I translate and whether there are corresponding resource files?

**Comment by pvermees** [comment]
Thanks a lot for the kind offer! I have just created a Chinese language option in the beta branch of the  [IsoplotRgui](https://github.com/pvermees/IsoplotRgui) repository. You can visit a live version of this app at:

[http://lgc.es.ucl.ac.uk/shiny/IsoplotR/](http://lgc.es.ucl.ac.uk/shiny/IsoplotR/)

(Click on 'Options' and 'Language'). There are two ways in which you can help me translated the entire site into Chinese:

First method (if you know a bit of programming):

1. fork [IsoplotRgui](https://github.com/pvermees/IsoplotRgui) from GitHub.
2. modify the html files in `/inst/shiny-examples/myapp/www/options/` and `/inst/shiny-examples/myapp/www/help/`. Take any English text string and surround it with `<en></en>` tags. Then add corresponding `<cn></cn>` tags immediately after them. For example:
`<en>Language</en><cn>语言</cn>`.
3. once you are done with this, then you can write a Chinese version of `/inst/shiny-examples/myapp/www/js/help.js`

Second method (if you don't know how to program): 

Copy the text in each of the options and help windows of the online GUI, translate them into Chinese and email them to me (`p.vermeesch[at]ucl.ac.uk`). I will insert the text in the app.

Cheers!

PV

**Comment by pvermees** [comment]
The welcome page and tutorial have already been translated into Chinese by [CycleUser](https://github.com/cycleuser). However he is busy finishing his PhD and doesn't have time to finish the work. It would be great if you could step in and translate the rest of the site. CycleUser suggested that we form a GitHub group to manage the project. Please drop me an email for further discussion.
